//installed packages
export {default as Modal} from '@material-tailwind/react/Modal'
export {default as ModalHeader} from '@material-tailwind/react/ModalHeader'
export {default as ModalBody} from '@material-tailwind/react/ModalBody'
export {default as ModalFooter} from '@material-tailwind/react/ModalFooter'
export {default as Button} from '@material-tailwind/react/Button'
export {default as Icon} from '@material-tailwind/react/Icon'
export {default as Tab} from '@material-tailwind/react/Tab'
export {default as TabItem} from '@material-tailwind/react/TabItem'
export {default as TabContent} from '@material-tailwind/react/TabContent'
export {default as TabList} from '@material-tailwind/react/TabList'
export {default as TabPane} from '@material-tailwind/react/TabPane' 
export {BsInfoLg, BsHddNetwork} from 'react-icons/bs'
export {BiSolidSchool} from 'react-icons/bi'
export {FcAcceptDatabase} from 'react-icons/fc'
export {FaConnectdevelop} from 'react-icons/fa'
export {SiBmcsoftware} from 'react-icons/si'
export {AiOutlineHome} from 'react-icons/ai'
//local components
export {default as Header} from './Header'
export {default as Sidebar} from './Sidebar'